using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.CustomControls
{
    [GenerateTypedNameReferences]
    public sealed partial class EntityClipboardWindow : DefaultWindow
    {
        public EntityClipboardWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }

}
